import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'
import type { NextPage } from "next";
import { useQuery } from "@apollo/client";
import { GetRoomsDocument } from "../graphql/dist/client";
import { GetRoomsQuery } from "../graphql/dist/client";

const Home: NextPage = () => {
  const { data } = useQuery<GetRoomsQuery>(GetRoomsDocument)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
      <div style={{ margin: "0 auto", width: "1000px" }}>
        {data?.rooms.map((room) =>(
          <div key={room.id}>
            <p>{room.host.name}</p>
            <p>room_id :{room.id}</p>
            <p>token: {room.token}</p>
          </div>
        ))}
      </div>
      </main>
    </>
  )
}

export default Home;
