import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'
import type { NextPage } from "next";
import { useMutation } from "@apollo/client";
import { CreateRoomDocument, CreateUserDocument } from "../graphql/dist/client";
import { CreateRoomMutation, CreateUserMutation } from "../graphql/dist/client";
import { useState } from 'react';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const [name, setName] = useState("")
  const router = useRouter()
  const token = router.query.c;
  const [createRoom, { data: room } ] = useMutation<CreateRoomMutation>(CreateRoomDocument)
  const [createUser, { data: user } ] = useMutation<CreateUserMutation>(CreateUserDocument)
  const pageTransition = (token :string | string[]) =>{
    if (!token){
      createRoom({
        variables:{
          host_name: name,
        }
      })
      if (room){
        router.push(`room/`)
      }
    }else{
      createUser({
        variables:{
          name: name,
          token: token,
        }
      })
      if (user){
        router.push(`room/`)
      }
  }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
      <div style={{ margin: "0 auto", width: "1000px" }}>
      </div>
      <div className={styles.home}>
          <div className={styles.frame}>
            <div className={styles.homediv1}>
              <div className={styles.homediv2}>
                <div className={styles.homediv3}>
                  <div className={styles.homediv4}>
                    <div className={styles.homediv5}>
                      <div className={styles.homespan}>
                        <span className={styles.hometext}>
                          <span>ユーザ登録</span>
                        </span>
                      </div>
                    </div>
                    <div className={styles.homediv6}>
                      <div className={styles.homesection}>
                        <div className={styles.homespan1}>
                          <span className={styles.hometext2}>
                            <span>ニックネームの入力</span>
                          </span>
                          <div className={styles.homeinput}>
                            <div className={styles.homedivplaceholder}>
                              <form id="inputform" 
                              onSubmit={(e)=>{
                                e.preventDefault();
                                if(token){
                                  pageTransition(token)
                                }else{
                                  pageTransition("")
                                }
                          
                                setName("");
                                router.push(`room/`)
                              }}
                              >
                                <input 
                                className={styles.hometext4} 
                                type="text"
                                value={name}
                                onChange={(e) =>{
                                    setName(e.currentTarget.value)
                                }}
                                />
                                </form>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className={styles.homediv7}>
                  <button type="submit" 
                  form="inputform" 
                  className={styles.homebutton}
                  >
                      <div className={styles.homei}>
                        {/* <Image
                          src="/imgs/icplaysvg.svg"
                          height={34}
                          width={27}
                          alt="icplaysvg"
                          className={styles.homeicplaysvg}
                        /> */}
                      </div>
                      <span className={styles.hometext6}>
                        <span>START</span>
                      </span>
                    </button>                  
                  </div>
                </div>
                <Image
                  src="/images/a.png"
                  height={105}
                  width={74}
                  alt="a"
                  className={styles.homeimg}
                  
                />
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}

export default Home;
